<!-- Page Header -->
<section>
    <h1><?= strtoupper($page->showTitle()) ?></h1>
    <?= $page->showBreadcrumbs() ?>
    <?= $page->showMessages() ?>
</section>
<!-- End Page Header -->

<style>
    #otp_mc {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    #otp_mc div {
        text-align: center;
    }
</style>

<section id="otp_mc">
    <div>
        <form id="otp_form" action="/_register/otp" method="post">
            <h1>Two Factor Authentication</h1>
            <p>Enter the 6-digit code generated by the Google Authenticator app on your phone.</p>
            <?php if (!$userStoredSecret) { ?>
            <p>Scan the picture to get the 6 digit code</p>
            <img src="<?= $qrCodeData ?>" alt="Scan this QR code" style="width: 200px; height: 200px;">
            <?php } ?>
            <p>Enter the 6 Digit Google Authenticator code:</p>
            <input type="text"
                id="verification_code"
                name="verification_code"
                maxlength="6"
                pattern="[0-9]{6}"
                inputmode="numeric"
                autocomplete="one-time-code"
                required>
            <input type="submit" value="Submit" />
        </form>
    </div>
</section>

<script>
    // Auto-submit when 6 digits are entered
    document.getElementById('verification_code').addEventListener('input', function(e) {
        if (this.value.length === 6) document.getElementById('otp_form').submit();
    });

    // Only allow numbers
    document.getElementById('verification_code').addEventListener('keydown', function(e) {
        if ((e.key < '0' || e.key > '9') && e.key !== 'Backspace' && e.key !== 'Delete' && e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') e.preventDefault();
    });
</script>
<?php
if ($isVerified) {
?>
    <script>
        setTimeout(function() {
            <?php if (empty($GLOBALS['_SESSION_']->refer_url)) $GLOBALS['_SESSION_']->refer_url = "/"; ?>
            window.location.href = "<?= $GLOBALS['_SESSION_']->refer_url ?>";
        }, 1000); // Redirect after 2 seconds
    </script>
<?php
}
?>
