<!-- Page Header -->
<section>
    <h1><?= strtoupper($page->showTitle()) ?></h1>
    <?= $page->showBreadcrumbs() ?>
    <?= $page->showMessages() ?>
</section>
<!-- End Page Header -->



<section id="otp_mc" class="register-otp-container">
    <div>
        <form id="otp_form" action="/_register/otp" method="post">
            <h1>Two Factor Authentication</h1>
            <?php if ($showQRCode) { ?>
                <p>Scan this QR code with <strong>Google Authenticator, Microsoft Authenticator, Authy, 1Password, or any compatible app</strong> to set up two-factor authentication (2FA).</p>
                <img src="<?= $qrCodeData ?>" alt="Scan this QR code" class="register-otp-qr-code">
                <div class="register-otp-description">
                    You can use any app that supports TOTP (Time-based One-Time Passwords).
                </div>
            <?php } else { ?>
                <div class="register-otp-message">
                    <p>You have a 2FA key set up to login to your account</p>
                    <p>Please enter the 6 digit code generated by your authenticator app.</p>
                </div>
            <?php } ?>
            <p>Enter the 6 digit code from your authenticator app:</p>
            <input type="text"
                id="verification_code"
                name="verification_code"
                maxlength="6"
                pattern="[0-9]{6}"
                inputmode="numeric"
                autocomplete="one-time-code">
            <input type="submit" value="Submit" />

            <div class="register-otp-app-links">
                <p>Don't have Google Authenticator?</p>
                <div class="register-otp-app-store">
                    <a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="_blank">
                        <img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/en-us" alt="Download on the App Store">
                    </a>
                    <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank">
                        <img src="https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" alt="Get it on Google Play" class="register-otp-google-play">
                    </a>
                </div>
            </div>

            <?php if (!$showQRCode) { ?>
                <div class="register-otp-recovery-links">
                    <p><a href="/_register/recover_otp">Can't access your authenticator? Recover 2FA setup</a></p>
                    <p><a href="/_register/backup_code">Use a backup code</a></p>
                </div>
            <?php } ?>

        </form>
    </div>
</section>

<script>
    // Auto-submit when 6 digits are entered
    document.getElementById('verification_code').addEventListener('input', function(e) {
        if (this.value.length === 6) document.getElementById('otp_form').submit();
    });

    // Only allow numbers
    document.getElementById('verification_code').addEventListener('keydown', function(e) {
        if ((e.key < '0' || e.key > '9') && e.key !== 'Backspace' && e.key !== 'Delete' && e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') e.preventDefault();
    });
</script>
<?php
if ($isVerified) {
?>
    <script>
        setTimeout(function() {
            <?php if (empty($GLOBALS['_SESSION_']->refer_url)) $GLOBALS['_SESSION_']->refer_url = "/"; ?>
            window.location.href = "<?= $GLOBALS['_SESSION_']->refer_url ?>";
        }, 1000); // Redirect after 2 seconds
    </script>
<?php
}
?>