version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: spectros-docker-mysql
        command: --default-authentication-plugin=mysql_native_password
        command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        working_dir: /application
        volumes:
          - .:/application
          - ./schema/create_schema.sql:/application/create_schema.sql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=spectros
          - MYSQL_DATABASE=spectros
          - MYSQL_USER=spectros
          - MYSQL_PASSWORD=spectros
        ports:
          - "8082:3306"
        command: --init-file /application/create_schema.sql
  website:
    container_name: spectros-docker-website
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ./../:/var/www/SpectrosWWW
    ports:
      - 8000:80
    depends_on:
      - mysql
